### ISSUE TITLE
asana.php missing in ext-lib

### ISSUE THREAD

**Issue by matthewwoo-zz** [edi-design/asana-hipchat#21]
Not sure where to post this question, so I filed an issue. Let me know if you need any more info, really want to use this integration :) 

**Getting this error when I run:** 
`php asana.php`

`Fatal error: require_once(): Failed opening required '/Users/mattw/asana_hipchat/ext-lib/asana.php' (include_path='.:') in /Users/mattw/asana_hipchat/asana.php on line 21`

**Version of PHP:**
PHP 5.5.14 (cli) (built: Sep  9 2014 19:09:25) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
mattw-mba-2:asana_hipchat mattw$ 

**Version of Sqlite:**
SQLite version 3.8.5 2014-08-15 22:37:57

**Comment by edi-design** [comment]
Hi Matthew,

take a look at the README file.
https://github.com/edi-design/asana-hipchat#script-installation

You have to download the dependencies into the ext-lib folder. I did not add them to the project, because they are developed by others.

If you have any other questions, feel free to ask.

André
